# Generated by Django 5.2.1 on 2025-05-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url-имя')),
                ('name', models.CharField(max_length=100, verbose_name='название бренда')),
                ('logo', models.ImageField(upload_to='products/', verbose_name='лого бренда')),
                ('description', models.TextField(verbose_name='описание бренда')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url-имя')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
                ('image', models.ImageField(upload_to='products/', verbose_name='фото категории')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url-имя')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='Скидка')),
                ('quantity', models.IntegerField(max_length=10, verbose_name='Количеество')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото продукта')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products_app.brand', verbose_name='Бренды')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products_app.category', verbose_name='Категория')),
            ],
        ),
    ]
